openapi: "3.0.3"
info:
  title: "Order Service — Payment API"
  description: "Payment sub-resource for the Order Service. Spec-driven: implementation follows this contract."
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "Local development server"

tags:
  - name: payments
    description: "Payment operations on orders"

paths:

  /api/orders/{orderId}/payments:

    post:
      tags: [payments]
      summary: "Make a payment for an order"
      operationId: createPayment
      parameters:
        - $ref: '#/components/parameters/OrderId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
            example:
              paymentMethod: "CREDIT_CARD"
              amount: 1549.99
              transactionReference: "TXN-ABC-12345"
      responses:
        "201":
          description: "Payment created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        "400":
          description: "Validation failure — amount mismatch or order not in PLACED status"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: "Order not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "409":
          description: "Payment already exists for this order"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      tags: [payments]
      summary: "Get the payment for an order"
      operationId: getPaymentByOrderId
      parameters:
        - $ref: '#/components/parameters/OrderId'
      responses:
        "200":
          description: "Payment record found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        "404":
          description: "Order or payment not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/orders/{orderId}/payments/refund:

    post:
      tags: [payments]
      summary: "Refund the payment for an order"
      operationId: refundPayment
      parameters:
        - $ref: '#/components/parameters/OrderId'
      responses:
        "200":
          description: "Payment refunded; order cancelled"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        "400":
          description: "Payment is not in SUCCESS status — cannot refund"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: "Order or payment not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:

  parameters:
    OrderId:
      name: orderId
      in: path
      required: true
      description: "The ID of the order"
      schema:
        type: integer
        format: int64
        example: 1

  schemas:

    PaymentMethod:
      type: string
      enum: [CREDIT_CARD, DEBIT_CARD, UPI, NET_BANKING]
      description: "Supported payment methods"

    PaymentStatus:
      type: string
      enum: [PENDING, SUCCESS, FAILED, REFUNDED]
      description: "Lifecycle status of a payment"

    PaymentRequest:
      type: object
      required: [paymentMethod, amount]
      properties:
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'
        amount:
          type: number
          format: double
          description: "Must exactly match order totalAmount"
          example: 1549.99
        transactionReference:
          type: string
          description: "Optional external transaction reference"
          example: "TXN-ABC-12345"

    PaymentResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        orderId:
          type: integer
          format: int64
          example: 1
        amount:
          type: number
          format: double
          example: 1549.99
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'
        status:
          $ref: '#/components/schemas/PaymentStatus'
        transactionReference:
          type: string
          example: "TXN-ABC-12345"
        paidAt:
          type: string
          format: date-time
          example: "2026-02-14T10:30:00"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: "Machine-readable error code"
          example: "AMOUNT_MISMATCH"
        message:
          type: string
          description: "Human-readable error description"
          example: "Payment amount 100.00 does not match order total 1549.99"
